#pragma once

/* GLSL Vertex */
"#version 330\n"
"layout(location=0) in vec2 Position;"
"layout(location=1) in vec2 TexCoord;"
"uniform mat4 u_MVP;"
"out vec2 v_TexCoord;"
"void main()"
"{"
  "gl_Position=u_MVP*vec4(Position,0.,1.),v_TexCoord=TexCoord;"
"}",

/* GLSL Fragment */
"#version 330\n"
"layout(location=0) out vec4 FragColor;layout(std140) uniform ubo_Metrics{vec2 u_OutSize;vec2 u_TexSize;vec2 u_RelSize;};"
"uniform sampler2D u_Texture;"
"in vec2 v_TexCoord;"
"const float u=2.;"
"const vec4 v=vec4(15.,15.,15.,15.);"
"const float n=48.,b=7.,x=6.;"
"const mat3x3 m=mat3x3(.299,.587,.114,-.169,-.331,.499,.499,-.418,-.0813),t=mat3x3(n*m[0],b*m[1],x*m[2]);"
"const vec4 z=vec4(.5,.5,.5,.5);"
"const float l=.65;"
"float e(vec3 z,vec3 e)"
"{"
  "return abs(dot(z-e,t[0]));"
"}"
"vec4 f(vec4 z,vec4 w)"
"{"
  "return vec4(abs(z-w));"
"}"
"bvec4 s(vec4 z,vec4 w)"
"{"
  "return lessThan(f(z,w),vec4(15.,15.,15.,15.));"
"}"
"bvec4 p(vec4 z,vec4 w)"
"{"
  "return lessThan(f(z,w),vec4(2.,2.,2.,2.));"
"}"
"bvec4 a(vec4 z,vec4 w)"
"{"
  "return lessThan(f(z,w),vec4(5.,5.,5.,5.));"
"}"
"vec4 a(vec4 z,vec4 w,vec4 e,vec4 u,vec4 v,vec4 x,vec4 s,vec4 y)"
"{"
  "return f(z,w)+f(z,e)+f(u,v)+f(u,x)+4.*f(s,y);"
"}"
"bvec4 i(bvec4 z,bvec4 w)"
"{"
  "return bvec4(z.x&&w.x,z.y&&w.y,z.z&&w.z,z.w&&w.w);"
"}"
"bvec4 c(bvec4 z,bvec4 w)"
"{"
  "return bvec4(z.x||w.x,z.y||w.y,z.z||w.z,z.w||w.w);"
"}"
"void main()"
"{"
  "vec2 v=v_TexCoord,w=u_RelSize;"
  "vec4 b=v.xxxy+vec4(-w.x,0,w.x,-2.*w.y),n=v.xxxy+vec4(-w.x,0,w.x,-w.y),x=v.xxxy+vec4(-w.x,0,w.x,0),y=v.xxxy+vec4(-w.x,0,w.x,w.y),m=v.xxxy+vec4(-w.x,0,w.x,2.*w.y),e=v.xyyy+vec4(-2.*w.x,-w.y,0,w.y),r=v.xyyy+vec4(2.*w.x,-w.y,0,w.y);"
  "bvec4 d,g,o,T,h,E,q,S,C,R,F;"
  "vec4 O,M,D,Z;"
  "vec2 Y=fract(v*u_TexSize);"
  "vec3 X=texture(u_Texture,b.xw).xyz,W=texture(u_Texture,b.yw).xyz,V=texture(u_Texture,b.zw).xyz,U=texture(u_Texture,n.xw).xyz,Q=texture(u_Texture,n.yw).xyz,P=texture(u_Texture,n.zw).xyz,N=texture(u_Texture,x.xw).xyz,L=texture(u_Texture,x.yw).xyz,K=texture(u_Texture,x.zw).xyz,J=texture(u_Texture,y.xw).xyz,I=texture(u_Texture,y.yw).xyz,H=texture(u_Texture,y.zw).xyz,G=texture(u_Texture,m.xw).xyz,B=texture(u_Texture,m.yw).xyz,A=texture(u_Texture,m.zw).xyz,k=texture(u_Texture,e.xy).xyz,j=texture(u_Texture,e.xz).xyz,aw=texture(u_Texture,e.xw).xyz,az=texture(u_Texture,r.xy).xyz,ae=texture(u_Texture,r.xz).xyz,ax=texture(u_Texture,r.xw).xyz;"
  "vec4 ay=t[0]*mat4x3(Q,N,I,K),at=t[0]*mat4x3(P,U,J,H),al=t[0]*mat4x3(L,L,L,L),an=ay.yzwx,ab=ay.wxyz,ad=at.zwxy,am=ay.zwxy,ag=at.wxyz,au=t[0]*mat4x3(ax,V,k,G),aL=t[0]*mat4x3(A,az,X,aw),av=t[0]*mat4x3(B,ae,W,j),aC=av.yzwx,ar=vec4(1.,-1.,-1.,1.),ac=vec4(1.,1.,-1.,-1.),ah=vec4(1.5,.5,-.5,.5),ai=vec4(1.,-1.,-1.,1.),aj=vec4(.5,2.,-.5,-2.),ak=vec4(1.,1.,-.5,0.),ao=vec4(1.,-1.,-1.,1.),aq=vec4(2.,.5,-2.,-.5),aA=vec4(2.,0.,-1.,.5);"
  "O=ar*Y.y+ac*Y.x;"
  "M=ai*Y.y+aj*Y.x;"
  "D=ao*Y.y+aq*Y.x;"
  "bvec4 aF=i(not(s(am,av)),not(s(am,aL))),aR=i(not(s(ab,aC)),not(s(ab,au))),as=i(not(s(am,an)),not(s(am,ad))),aB=i(not(s(ab,ay)),not(s(ab,at))),aD=i(s(al,ag),c(aR,aF)),aE=c(aB,c(as,c(aD,c(s(al,ad),s(al,at)))));"
  "h=i(notEqual(al,ab),i(notEqual(al,am),aE));"
  "E=i(notEqual(al,ad),notEqual(an,ad));"
  "q=i(notEqual(al,at),notEqual(ay,at));"
  "vec4 aM=smoothstep(ah-z,ah+z,O),aO=smoothstep(ak-z,ak+z,M),aT=smoothstep(aA-z,aA+z,D);"
  "d=i(lessThan(a(al,at,ad,ag,av,aC,am,ab)+3.5,a(am,an,aL,ab,au,ay,al,ag)),h);"
  "g=i(lessThanEqual(u*f(ab,ad),f(am,at)),E);"
  "o=i(greaterThanEqual(f(ab,ad),u*f(am,at)),q);"
  "F=i(d,bvec4(aM));"
  "C=i(d,i(g,bvec4(aO)));"
  "R=i(d,i(o,bvec4(aT)));"
  "T=lessThanEqual(f(al,ab),f(al,am));"
  "vec3 aI=L,aN,aQ,aK,aJ,aY,aP,aG,aH,aW;"
  "aN=W;"
  "aQ=Q;"
  "aY=L;"
  "aK=I;"
  "aJ=B;"
  "aP=aQ-aN;"
  "aG=aY-aQ;"
  "aH=aK-aY;"
  "aW=aJ-aK;"
  "vec3 aS=(7.*(aG+aH)-3.*(aP+aW))/16.,aU;"
  "aU.x=aY.x<.5?2.*aY.x:2.*(1.-aY.x);"
  "aU.y=aY.y<.5?2.*aY.y:2.*(1.-aY.y);"
  "aU.z=aY.z<.5?2.*aY.z:2.*(1.-aY.z);"
  "aU=min(aU,l*abs(aG));"
  "aU=min(aU,l*abs(aH));"
  "aS=clamp(aS,-aU,aU);"
  "vec3 aV=(2.*Y.y-1.)*aS+aY;"
  "aN=j;"
  "aQ=N;"
  "aY=aV;"
  "aK=K;"
  "aJ=ae;"
  "aP=aQ-aN;"
  "aG=aY-aQ;"
  "aH=aK-aY;"
  "aW=aJ-aK;"
  "aS=(7.*(aG+aH)-3.*(aP+aW))/16.;"
  "aU.x=aY.x<.5?2.*aY.x:2.*(1.-aY.x);"
  "aU.y=aY.y<.5?2.*aY.y:2.*(1.-aY.y);"
  "aU.z=aY.z<.5?2.*aY.z:2.*(1.-aY.z);"
  "aU=min(aU,l*abs(aG));"
  "aU=min(aU,l*abs(aH));"
  "aS=clamp(aS,-aU,aU);"
  "vec3 aX=(2.*Y.x-1.)*aS+aY;"
  "S=c(C,c(R,F));"
  "float aa=0.;"
  "vec3 aZ;"
  "vec4 af=mix(al,ab,d);"
  "bool ap=false;"
  "bvec4 bw;"
  "if(all(a(af,al)))"
    "ap=true,aZ=aI=aX;"
  "else "
     "aZ=aI=L;"
  "bw=i(bvec4(ap),p(al,mix(ab,am,T)));"
  "vec4 bv=vec4(F)*aM,bz=vec4(C)*aO,by=vec4(R)*aT,bx=max(max(bz,by),bv);"
  "if(S.x)"
    "{"
      "aZ=T.x?K:I;"
      "aa=bx.x;"
      "if(bw.x)"
        "aZ=aI=aX;"
      "else "
         "aI=L;"
    "}"
  "else "
     "if(S.y)"
      "{"
        "aZ=T.y?Q:K;"
        "aa=bx.y;"
        "if(bw.y)"
          "aZ=aI=aX;"
        "else "
           "aI=L;"
      "}"
    "else "
       "if(S.z)"
        "{"
          "aZ=T.z?N:Q;"
          "aa=bx.z;"
          "if(bw.z)"
            "aZ=aI=aX;"
          "else "
             "aI=L;"
        "}"
      "else "
         "if(S.w)"
          "{"
            "aZ=T.w?I:N;"
            "aa=bx.w;"
            "if(bw.w)"
              "aZ=aI=aX;"
            "else "
               "aI=L;"
          "}"
  "FragColor=vec4(clamp(mix(aI,aZ,aa),0.,1.),1.);"
"}",

/* GLSL Compute */
nullptr,