#pragma once

"#ifdef VERTEX\n"
"layout(location=0) in vec2 Position;"
"layout(location=1) in vec2 TexCoord;"
"uniform mat4 u_MVP;"
"out vec2 v_TexCoord;"
"void main()"
"{"
  "gl_Position=u_MVP*vec4(Position,0,1);"
  "v_TexCoord=TexCoord;"
"}"
"\n#elif FRAGMENT\n"
"layout(location=0) out vec4 FragColor;layout(std140) uniform ubo_Metrics{vec2 u_OutSize;vec2 u_TexSize;vec2 u_RelSize;};"
"uniform sampler2D u_Texture;"
"in vec2 v_TexCoord;"
"vec3 v=vec3(1);"
"void main()"
"{"
  "float u=u_RelSize.x*.5,w=u_RelSize.y*.5;"
  "vec4 e,z,l,d;"
  "e.xy=v_TexCoord+vec2(-u,0);"
  "z.xy=v_TexCoord+vec2(u,0);"
  "l.xy=v_TexCoord+vec2(0,-w);"
  "d.xy=v_TexCoord+vec2(0,w);"
  "e.zw=v_TexCoord+vec2(-u,-w);"
  "z.zw=v_TexCoord+vec2(-u,w);"
  "l.zw=v_TexCoord+vec2(u,-w);"
  "d.zw=v_TexCoord+vec2(u,w);"
  "vec3 a=texture(u_Texture,e.zw).xyz,n=texture(u_Texture,l.xy).xyz,y=texture(u_Texture,l.zw).xyz,P=texture(u_Texture,e.xy).xyz,r=texture(u_Texture,v_TexCoord).xyz,A=texture(u_Texture,z.xy).xyz,C=texture(u_Texture,z.zw).xyz,D=texture(u_Texture,d.xy).xyz,E=texture(u_Texture,d.zw).xyz;"
  "float m=dot(abs(a-E),v)+1e-4,x=dot(abs(y-C),v)+1e-4,s=dot(abs(P-A),v)+1e-4,F=dot(abs(n-D),v)+1e-4,f=.5*(s+F),i=.5*(m+x);"
  "vec3 T=(s*(n+D)+F*(P+A)+f*r)/(2.5*(s+F)),B=(m*(y+C)+x*(a+E)+i*r)/(2.5*(m+x));"
  "f=dot(abs(T-r),v)+1e-4;"
  "i=dot(abs(B-r),v)+1e-4;"
  "FragColor=vec4((f*B+i*T)/(f+i),1);"
"}"
"\n#endif"