#pragma once

"#ifdef VERTEX\n"
"layout(location=0) in vec2 Position;"
"layout(location=1) in vec2 TexCoord;"
"uniform mat4 u_MVP;"
"out vec2 v_TexCoord;"
"void main()"
"{"
  "gl_Position=u_MVP*vec4(Position,0,1);"
  "v_TexCoord=TexCoord;"
"}"
"\n#elif FRAGMENT\n"
"layout(location=0) out vec4 FragColor;layout(std140) uniform ubo_Metrics{vec2 u_OutSize;vec2 u_TexSize;vec2 u_RelSize;};"
"uniform sampler2D u_Texture;"
"in vec2 v_TexCoord;"
"\n#define mul(c,d)(d*c)\n"
"void main()"
"{"
  "vec2 u=v_TexCoord*u_TexSize,v=floor(u-.5)+.5,t=u-v,m=t*(-.5+t*(1.-.5*t)),n=1.+t*t*(-2.5+1.5*t),y=t*(.5+t*(2.-1.5*t)),d=t*t*(-.5+.5*t),r=n+y,l=v-1.,P=v+2.,F=v+y/(n+y);"
  "l*=u_RelSize;"
  "P*=u_RelSize;"
  "F*=u_RelSize;"
  "vec4 e=texture(u_Texture,vec2(l.xy)),x=texture(u_Texture,vec2(F.x,l.y)),c=texture(u_Texture,vec2(P.x,l.y)),s=texture(u_Texture,vec2(l.x,F.y)),A=texture(u_Texture,vec2(F.xy)),C=texture(u_Texture,vec2(P.x,F.y)),D=texture(u_Texture,vec2(l.x,P.y)),E=texture(u_Texture,vec2(F.x,P.y)),G=texture(u_Texture,vec2(P.xy)),i,o,B,H,I=vec4(0),J=vec4(0,0,0,1);"
  "H=vec4(m.x,r.x,d.x,1);"
  "I=vec4(m.y,r.y,d.y,1);"
  "i=vec4(mul(H,mat4(e,x,c,J)));"
  "o=vec4(mul(H,mat4(s,A,C,J)));"
  "B=vec4(mul(H,mat4(D,E,G,J)));"
  "FragColor=mul(I,mat4(i,o,B,J));"
"}"
"\n#endif"