#pragma once

/* GLSL Vertex */
"#version 330\n"
"layout(location=0) in vec2 Position;"
"layout(location=1) in vec2 TexCoord;"
"uniform mat4 u_MVP;"
"out vec2 v_TexCoord;"
"void main()"
"{"
  "gl_Position=u_MVP*vec4(Position,0.,1.),v_TexCoord=TexCoord;"
"}",

/* GLSL Fragment */
"#version 330\n"
"layout(location=0) out vec4 FragColor;layout(std140) uniform ubo_Metrics{vec2 u_OutSize;vec2 u_TexSize;vec2 u_RelSize;};"
"uniform sampler2D u_Texture;"
"in vec2 v_TexCoord;"
"vec4 u(vec4 u,vec4 w)"
"{"
  "return vec4(abs(u-w));"
"}"
"vec4 v(vec4 u,vec4 w)"
"{"
  "return vec4(notEqual(u,w));"
"}"
"vec4 u(vec4 z,vec4 w,vec4 e,vec4 x,vec4 v,vec4 y,vec4 g,vec4 s)"
"{"
  "return u(z,w)+u(z,e)+u(x,v)+u(x,y)+4.*u(g,s);"
"}"
"void main()"
"{"
  "vec2 t=v_TexCoord,m=u_RelSize;"
  "vec4 w=t.xxxy+vec4(-m.x,0.,m.x,-2.*m.y),s=t.xxxy+vec4(-m.x,0.,m.x,-m.y),e=t.xxxy+vec4(-m.x,0.,m.x,0.),r=t.xxxy+vec4(-m.x,0.,m.x,m.y),y=t.xxxy+vec4(-m.x,0.,m.x,2.*m.y),n=t.xyyy+vec4(-2.*m.x,-m.y,0.,m.y),x=t.xyyy+vec4(2.*m.x,-m.y,0.,m.y),z,g,i,l,d,b,F,c;"
  "bvec4 a,T;"
  "vec4 o,p,S;"
  "vec2 C=fract(t*u_TexSize);"
  "vec3 h=texture(u_Texture,w.xw).xyz,f=texture(u_Texture,w.yw).xyz,R=texture(u_Texture,w.zw).xyz,E=texture(u_Texture,s.xw).xyz,q=texture(u_Texture,s.yw).xyz,O=texture(u_Texture,s.zw).xyz,M=texture(u_Texture,e.xw).xyz,D=texture(u_Texture,e.yw).xyz,Z=texture(u_Texture,e.zw).xyz,Y=texture(u_Texture,r.xw).xyz,X=texture(u_Texture,r.yw).xyz,W=texture(u_Texture,r.zw).xyz,V=texture(u_Texture,y.xw).xyz,U=texture(u_Texture,y.yw).xyz,Q=texture(u_Texture,y.zw).xyz,P=texture(u_Texture,n.xy).xyz,N=texture(u_Texture,n.xz).xyz,L=texture(u_Texture,n.xw).xyz,K=texture(u_Texture,x.xy).xyz,J=texture(u_Texture,x.xz).xyz,I=texture(u_Texture,x.xw).xyz;"
  "vec4 H=vec3(.2126,.7152,.0722)*mat4x3(q,M,X,Z),G=vec3(.2126,.7152,.0722)*mat4x3(O,E,Y,W),B=vec3(.2126,.7152,.0722)*mat4x3(D,D,D,D),A=H.yzwx,k=H.wxyz,j=G.zwxy,ae=H.zwxy,az=G.wxyz,ax=vec3(.2126,.7152,.0722)*mat4x3(I,R,P,V),at=vec3(.2126,.7152,.0722)*mat4x3(Q,K,h,L),am=vec3(.2126,.7152,.0722)*mat4x3(U,J,f,N),aB=am.yzwx,an=vec4(1.,-1.,-1.,1.),ab=vec4(1.,1.,-1.,-1.),aw=vec4(1.5,.5,-.5,.5),ag=vec4(1.,-1.,-1.,1.),al=vec4(.5,2.,-.5,-2.),ay=vec4(1.,1.,-.5,0.),ai=vec4(1.,-1.,-1.,1.),ar=vec4(2.,.5,-2.,-.5),aj=vec4(2.,0.,-1.,.5);"
  "o=vec4(greaterThan(an*C.y+ab*C.x,aw));"
  "p=vec4(greaterThan(ag*C.y+al*C.x,ay));"
  "S=vec4(greaterThan(ai*C.y+ar*C.x,aj));"
  "d=v(B,k)*v(B,ae);"
  "b=v(B,j)*v(A,j);"
  "F=v(B,G)*v(H,G);"
  "vec4 aD=u(B,G,j,az,am,aB,ae,k),aG=u(ae,A,at,k,ax,H,B,az);"
  "z=step(aD,aG)*d;"
  "g=step(aD+vec4(.1,.1,.1,.1),aG)*step(vec4(.5,.5,.5,.5),d);"
  "i=step(2.*u(k,j),u(ae,G))*b*g;"
  "l=step(2.*u(ae,G),u(k,j))*F*g;"
  "a=bvec4(g*(o+i*p)+l*S);"
  "T=lessThanEqual(u(B,k),u(B,ae));"
  "vec3 ak=a.x?T.x?Z:X:a.y?T.y?q:Z:a.z?T.z?M:q:D,ad=a.w?T.w?X:M:a.z?T.z?M:q:a.y?T.y?q:Z:D;"
  "vec2 aa=abs(vec3(.2126,.7152,.0722)*mat2x3(ak,ad)-B.xy);"
  "FragColor=vec4(mix(ak,ad,step(aa.x,aa.y)),1.);"
"}",

/* GLSL Compute */
nullptr,