#pragma once

/* GLSL Vertex */
"#version 330\n"
"layout(location=0) in vec2 Position;"
"layout(location=1) in vec2 TexCoord;"
"uniform mat4 u_MVP;"
"out vec2 v_TexCoord;"
"void main()"
"{"
  "gl_Position=u_MVP*vec4(Position,0.,1.),v_TexCoord=TexCoord;"
"}",

/* GLSL Fragment */
"#version 330\n"
"layout(location=0) out vec4 FragColor;layout(std140) uniform ubo_Metrics{vec2 u_OutSize;vec2 u_TexSize;vec2 u_RelSize;};"
"uniform sampler2D u_Texture;"
"in vec2 v_TexCoord;"
"float u(vec3 e,vec3 z)"
"{"
  "const vec3 u=vec3(.2627,.678,.0593);"
  "const float v=.5/(1.-u.z),t=.5/(1.-u.x);"
  "vec3 s=e-z;"
  "float x=dot(s.xyz,u),y=v*(s.z-x),w=t*(s.x-x);"
  "return sqrt(x*x+y*y+w*w);"
"}"
"bool e(const vec3 e,const vec3 v)"
"{"
  "return u(e,v)<30./255.;"
"}"
"float e(vec2 e,vec2 z,vec2 u,vec2 v)"
"{"
  "vec2 t=e-z,s=u*(dot(t,u)/dot(u,u)),x=t-s,w=vec2(-u.y,u.x);"
  "float m=sign(dot(t,w)),y=m*length(x*v);"
  "return smoothstep(-sqrt(2.)/2.,sqrt(2.)/2.,y);"
"}"
"void main()"
"{"
  "vec2 v=u_OutSize*u_RelSize,t=fract(v_TexCoord*u_TexSize)-vec2(.5,.5),y=v_TexCoord-t*u_RelSize;"
  "vec3 z=texture(u_Texture,y+u_RelSize*vec2(-1.,-1.)).xyz,x=texture(u_Texture,y+u_RelSize*vec2(0.,-1.)).xyz,s=texture(u_Texture,y+u_RelSize*vec2(1.,-1.)).xyz,w=texture(u_Texture,y+u_RelSize*vec2(-1.,0.)).xyz,m=texture(u_Texture,y+u_RelSize*vec2(0.,0.)).xyz,d=texture(u_Texture,y+u_RelSize*vec2(1.,0.)).xyz,c=texture(u_Texture,y+u_RelSize*vec2(-1.,1.)).xyz,r=texture(u_Texture,y+u_RelSize*vec2(0.,1.)).xyz,i=texture(u_Texture,y+u_RelSize*vec2(1.,1.)).xyz;"
  "ivec4 b=ivec4(0,0,0,0);"
  "if(!(m==d&&r==i||m==r&&d==i))"
    "{"
      "float f=u(c,m)+u(m,s)+u(texture(u_Texture,y+u_RelSize*vec2(0,2)).xyz,i)+u(i,texture(u_Texture,y+u_RelSize*vec2(2.,0.)).xyz)+4.*u(r,d),n=u(w,r)+u(r,texture(u_Texture,y+u_RelSize*vec2(1,2)).xyz)+u(x,d)+u(d,texture(u_Texture,y+u_RelSize*vec2(2.,1.)).xyz)+4.*u(m,i);"
      "bool o=3.6*f<n;"
      "b.z=f<n&&m!=d&&m!=r?o?2:1:0;"
    "}"
  "if(!(w==m&&c==r||w==c&&m==r))"
    "{"
      "float f=u(texture(u_Texture,y+u_RelSize*vec2(-2.,1.)).xyz,w)+u(w,x)+u(texture(u_Texture,y+u_RelSize*vec2(-1.,2.)).xyz,r)+u(r,d)+4.*u(c,m),n=u(texture(u_Texture,y+u_RelSize*vec2(-2.,0.)).xyz,c)+u(c,texture(u_Texture,y+u_RelSize*vec2(0.,2.)).xyz)+u(z,m)+u(m,i)+4.*u(w,r);"
      "bool o=3.6*n<f;"
      "b.w=f>n&&m!=w&&m!=r?o?2:1:0;"
    "}"
  "if(!(x==s&&m==d||x==m&&s==d))"
    "{"
      "float f=u(w,x)+u(x,texture(u_Texture,y+u_RelSize*vec2(1.,-2.)).xyz)+u(r,d)+u(d,texture(u_Texture,y+u_RelSize*vec2(2.,-1.)).xyz)+4.*u(m,s),n=u(z,m)+u(m,i)+u(texture(u_Texture,y+u_RelSize*vec2(0.,-2.)).xyz,s)+u(s,texture(u_Texture,y+u_RelSize*vec2(2.,0.)).xyz)+4.*u(x,d);"
      "bool o=3.6*n<f;"
      "b.y=f>n&&m!=x&&m!=d?o?2:1:0;"
    "}"
  "if(!(z==x&&w==m||z==w&&x==m))"
    "{"
      "float f=u(texture(u_Texture,y+u_RelSize*vec2(-2.,0.)).xyz,z)+u(z,texture(u_Texture,y+u_RelSize*vec2(0.,-2.)).xyz)+u(c,m)+u(m,s)+4.*u(w,x),n=u(texture(u_Texture,y+u_RelSize*vec2(-2.,-1.)).xyz,w)+u(w,r)+u(texture(u_Texture,y+u_RelSize*vec2(-1.,-2.)).xyz,x)+u(x,d)+4.*u(z,m);"
      "bool o=3.6*f<n;"
      "b.x=f<n&&m!=w&&m!=x?o?2:1:0;"
    "}"
  "vec3 f=m;"
  "if(b.z!=0)"
    "{"
      "float n=u(d,c),o=u(r,s);"
      "bool l=b.z==2||!(b.y!=0&&!e(m,c)||b.w!=0&&!e(m,s)||e(c,r)&&e(r,i)&&e(i,d)&&e(d,s)&&!e(m,i));"
      "vec2 F=vec2(0.,1./sqrt(2.)),S=vec2(1.,-1.);"
      "if(l)"
        "{"
          "bool T=2.2*n<=o&&m!=c&&w!=c,R=2.2*o<=n&&m!=s&&x!=s;"
          "F=T?vec2(0.,.25):vec2(0.,.5);"
          "S.x+=T?1.:0.;"
          "S.y-=R?1.:0.;"
        "}"
      "vec3 T=mix(r,d,step(u(m,d),u(m,r)));"
      "f=mix(f,T,e(t,F,S,v));"
    "}"
  "if(b.w!=0)"
    "{"
      "float n=u(r,z),o=u(w,i);"
      "bool l=b.w==2||!(b.z!=0&&!e(m,z)||b.x!=0&&!e(m,i)||e(z,w)&&e(w,c)&&e(c,r)&&e(r,i)&&!e(m,c));"
      "vec2 F=vec2(-1./sqrt(2.),0.),S=vec2(1.,1.);"
      "if(l)"
        "{"
          "bool T=2.2*n<=o&&m!=z&&x!=z,R=2.2*o<=n&&m!=i&&d!=i;"
          "F=T?vec2(-.25,0.):vec2(-.5,0.);"
          "S.y+=T?1.:0.;"
          "S.x+=R?1.:0.;"
        "}"
      "vec3 T=mix(r,w,step(u(m,w),u(m,r)));"
      "f=mix(f,T,e(t,F,S,v));"
    "}"
  "if(b.y!=0)"
    "{"
      "float n=u(x,i),o=u(d,z);"
      "bool l=b.y==2||!(b.x!=0&&!e(m,i)||b.z!=0&&!e(m,z)||e(i,d)&&e(d,s)&&e(s,x)&&e(x,z)&&!e(m,s));"
      "vec2 F=vec2(1./sqrt(2.),0.),S=vec2(-1.,-1.);"
      "if(l)"
        "{"
          "bool T=2.2*n<=o&&m!=i&&r!=i,R=2.2*o<=n&&m!=z&&w!=z;"
          "F=T?vec2(.25,0.):vec2(.5,0.);"
          "S.y-=T?1.:0.;"
          "S.x-=R?1.:0.;"
        "}"
      "vec3 T=mix(d,x,step(u(m,x),u(m,d)));"
      "f=mix(f,T,e(t,F,S,v));"
    "}"
  "if(b.x!=0)"
    "{"
      "float n=u(w,s),o=u(x,c);"
      "bool l=b.x==2||!(b.w!=0&&!e(m,s)||b.y!=0&&!e(m,c)||e(s,x)&&e(x,z)&&e(z,w)&&e(w,c)&&!e(m,z));"
      "vec2 F=vec2(0.,-1./sqrt(2.)),S=vec2(-1.,1.);"
      "if(l)"
        "{"
          "bool T=2.2*n<=o&&m!=s&&d!=s,R=2.2*o<=n&&m!=c&&r!=c;"
          "F=T?vec2(0.,-.25):vec2(0.,-.5);"
          "S.x-=T?1.:0.;"
          "S.y+=R?1.:0.;"
        "}"
      "vec3 T=mix(w,x,step(u(m,x),u(m,w)));"
      "f=mix(f,T,e(t,F,S,v));"
    "}"
  "FragColor=vec4(f,1.);"
"}",

/* GLSL Compute */
nullptr,