#pragma once

"#ifdef VERTEX\n"
"layout(location=0) in vec2 Position;"
"layout(location=1) in vec2 TexCoord;"
"uniform mat4 u_MVP;"
"out vec2 v_TexCoord;"
"void main()"
"{"
  "gl_Position=u_MVP*vec4(Position,0,1);"
  "v_TexCoord=TexCoord;"
"}"
"\n#elif FRAGMENT\n"
"layout(location=0) out vec4 FragColor;layout(std140) uniform ubo_Metrics{vec2 u_OutSize;vec2 u_TexSize;vec2 u_RelSize;};"
"uniform sampler2D u_Texture;"
"in vec2 v_TexCoord;"
"float q(vec3 v,vec3 u)"
"{"
  "const vec3 s=vec3(.2627,.678,.0593);"
  "vec3 n=v-u;"
  "float q=dot(n.xyz,s),y=.5/(1.-s.z)*(n.z-q),b=.5/(1.-s.x)*(n.x-q);"
  "return sqrt(q*q+y*y+b*b);"
"}"
"bool n(const vec3 v,const vec3 s)"
"{"
  "return q(v,s)<30./255.;"
"}"
"float n(vec2 v,vec2 u,vec2 q,vec2 s)"
"{"
  "vec2 n=v-u,b=q*(dot(n,q)/dot(q,q)),y=vec2(-q.y,q.x);"
  "float m=sign(dot(n,y)),x=m*length((n-b)*s);"
  "return smoothstep(-sqrt(2.)/2.,sqrt(2.)/2.,x);"
"}"
"\n#define eq(a,b)(a==b)\n"
"\n#define neq(a,b)(a!=b)\n"
"\n#define P(x,y)texture(u_Texture,coord+u_RelSize*vec2(x,y)).rgb\n"
"void main()"
"{"
  "vec2 s=u_OutSize*u_RelSize,v=fract(v_TexCoord*u_TexSize)-vec2(.5);"
  "vec3 u=P(-1.,-1.),y=P(0.,-1.),b=P(1.,-1.),x=P(-1.,0.),e=P(0.,0.),a=P(1.,0.),z=P(-1.,1.),c=P(0.,1.),d=P(1.,1.);"
  "ivec4 m=ivec4(0,0,0,0);"
  "if(!(eq(e,a)&&eq(c,d)||eq(e,c)&&eq(a,d)))"
    "{"
      "float i=q(z,e)+q(e,b)+q(P(0,2),d)+q(d,P(2.,0.))+4.*q(c,a),w=q(x,c)+q(c,P(1,2))+q(y,a)+q(a,P(2.,1.))+4.*q(e,d);"
      "m.z=i<w&&neq(e,a)&&neq(e,c)?"
        "3.6*i<w?"
          "2:"
          "1:"
        "0;"
    "}"
  "if(!(eq(x,e)&&eq(z,c)||eq(x,z)&&eq(e,c)))"
    "{"
      "float i=q(P(-2.,1.),x)+q(x,y)+q(P(-1.,2.),c)+q(c,a)+4.*q(z,e),w=q(P(-2.,0.),z)+q(z,P(0.,2.))+q(u,e)+q(e,d)+4.*q(x,c);"
      "m.w=i>w&&neq(e,x)&&neq(e,c)?"
        "3.6*w<i?"
          "2:"
          "1:"
        "0;"
    "}"
  "if(!(eq(y,b)&&eq(e,a)||eq(y,e)&&eq(b,a)))"
    "{"
      "float i=q(x,y)+q(y,P(1.,-2.))+q(c,a)+q(a,P(2.,-1.))+4.*q(e,b),w=q(u,e)+q(e,d)+q(P(0.,-2.),b)+q(b,P(2.,0.))+4.*q(y,a);"
      "m.y=i>w&&neq(e,y)&&neq(e,a)?"
        "3.6*w<i?"
          "2:"
          "1:"
        "0;"
    "}"
  "if(!(eq(u,y)&&eq(x,e)||eq(u,x)&&eq(y,e)))"
    "{"
      "float i=q(P(-2.,0.),u)+q(u,P(0.,-2.))+q(z,e)+q(e,b)+4.*q(x,y),w=q(P(-2.,-1.),x)+q(x,c)+q(P(-1.,-2.),y)+q(y,a)+4.*q(u,e);"
      "m.x=i<w&&neq(e,x)&&neq(e,y)?"
        "3.6*i<w?"
          "2:"
          "1:"
        "0;"
    "}"
  "vec3 i=e;"
  "if(m.z!=0)"
    "{"
      "float w=q(a,z),T=q(c,b);"
      "bool l=m.z==2||!(m.y!=0&&!n(e,z)||m.w!=0&&!n(e,b)||n(z,c)&&n(c,d)&&n(d,a)&&n(a,b)&&!n(e,d));"
      "vec2 f=vec2(0,1./sqrt(2.)),r=vec2(1,-1);"
      "if(l)"
        "{"
          "bool F=2.2*w<=T&&neq(e,z)&&neq(x,z),A=2.2*T<=w&&neq(e,b)&&neq(y,b);"
          "f=F?"
            "vec2(0,.25):"
            "vec2(0,.5);"
          "r.x+=F?"
            "1.:"
            "0.;"
          "r.y-=A?"
            "1.:"
            "0.;"
        "}"
      "vec3 F=mix(c,a,step(q(e,a),q(e,c)));"
      "i=mix(i,F,n(v,f,r,s));"
    "}"
  "if(m.w!=0)"
    "{"
      "float w=q(c,u),T=q(x,d);"
      "bool l=m.w==2||!(m.z!=0&&!n(e,u)||m.x!=0&&!n(e,d)||n(u,x)&&n(x,z)&&n(z,c)&&n(c,d)&&!n(e,z));"
      "vec2 f=vec2(-1./sqrt(2.),0),r=vec2(1);"
      "if(l)"
        "{"
          "bool F=2.2*w<=T&&neq(e,u)&&neq(y,u),A=2.2*T<=w&&neq(e,d)&&neq(a,d);"
          "f=F?"
            "vec2(-.25,0):"
            "vec2(-.5,0);"
          "r.y+=F?"
            "1.:"
            "0.;"
          "r.x+=A?"
            "1.:"
            "0.;"
        "}"
      "vec3 F=mix(c,x,step(q(e,x),q(e,c)));"
      "i=mix(i,F,n(v,f,r,s));"
    "}"
  "if(m.y!=0)"
    "{"
      "float w=q(y,d),T=q(a,u);"
      "bool l=m.y==2||!(m.x!=0&&!n(e,d)||m.z!=0&&!n(e,u)||n(d,a)&&n(a,b)&&n(b,y)&&n(y,u)&&!n(e,b));"
      "vec2 f=vec2(1./sqrt(2.),0),r=vec2(-1);"
      "if(l)"
        "{"
          "bool F=2.2*w<=T&&neq(e,d)&&neq(c,d),A=2.2*T<=w&&neq(e,u)&&neq(x,u);"
          "f=F?"
            "vec2(.25,0):"
            "vec2(.5,0);"
          "r.y-=F?"
            "1.:"
            "0.;"
          "r.x-=A?"
            "1.:"
            "0.;"
        "}"
      "vec3 F=mix(a,y,step(q(e,y),q(e,a)));"
      "i=mix(i,F,n(v,f,r,s));"
    "}"
  "if(m.x!=0)"
    "{"
      "float w=q(x,b),T=q(y,z);"
      "bool l=m.x==2||!(m.w!=0&&!n(e,b)||m.y!=0&&!n(e,z)||n(b,y)&&n(y,u)&&n(u,x)&&n(x,z)&&!n(e,u));"
      "vec2 f=vec2(0,-1./sqrt(2.)),r=vec2(-1,1);"
      "if(l)"
        "{"
          "bool F=2.2*w<=T&&neq(e,b)&&neq(a,b),A=2.2*T<=w&&neq(e,z)&&neq(c,z);"
          "f=F?"
            "vec2(0,-.25):"
            "vec2(0,-.5);"
          "r.x-=F?"
            "1.:"
            "0.;"
          "r.y+=A?"
            "1.:"
            "0.;"
        "}"
      "vec3 F=mix(x,y,step(q(e,y),q(e,x)));"
      "i=mix(i,F,n(v,f,r,s));"
    "}"
  "FragColor=vec4(i,1);"
"}"
"\n#endif"