#pragma once

"#ifdef VERTEX\n"
"layout(location=0) in vec2 Position;"
"layout(location=1) in vec2 TexCoord;"
"uniform mat4 u_MVP;"
"out vec2 v_TexCoord;"
"void main()"
"{"
  "gl_Position=u_MVP*vec4(Position,0,1);"
  "v_TexCoord=TexCoord;"
"}"
"\n#elif FRAGMENT\n"
"layout(location=0) out vec4 FragColor;layout(std140) uniform ubo_Metrics{vec2 u_OutSize;vec2 u_TexSize;vec2 u_RelSize;};"
"uniform sampler2D u_Texture;"
"in vec2 v_TexCoord;"
"float q(vec3 v,vec3 e)"
"{"
  "const vec3 s=vec3(.2627,.678,.0593);"
  "vec3 u=v-e;"
  "float q=dot(u.xyz,s),y=.5/(1.-s.z)*(u.z-q),b=.5/(1.-s.x)*(u.x-q);"
  "return sqrt(q*q+y*y+b*b);"
"}"
"bool n(const vec3 v,const vec3 s)"
"{"
  "return q(v,s)<30./255.;"
"}"
"float n(vec2 v,vec2 s,vec2 q,vec2 u)"
"{"
  "vec2 x=v-s,b=q*(dot(x,q)/dot(q,q)),y=vec2(-q.y,q.x);"
  "float m=sign(dot(x,y)),n=m*length((x-b)*u);"
  "return smoothstep(-sqrt(2.)/2.,sqrt(2.)/2.,n);"
"}"
"\n#define eq(a,b)(a==b)\n"
"\n#define neq(a,b)(a!=b)\n"
"vec2 coord;"
"\n#define P(x,y)texture(u_Texture,coord+u_RelSize*vec2(x,y)).rgb\n"
"void main()"
"{"
  "vec2 s=u_OutSize*u_RelSize,v=fract(v_TexCoord*u_TexSize)-vec2(.5);"
  "coord=v_TexCoord-v*u_RelSize;"
  "vec3 u=P(-1.,-1.),x=P(0.,-1.),y=P(1.,-1.),b=P(-1.,0.),e=P(0.,0.),a=P(1.,0.),d=P(-1.,1.),z=P(0.,1.),c=P(1.,1.);"
  "ivec4 m=ivec4(0,0,0,0);"
  "if(!(eq(e,a)&&eq(z,c)||eq(e,z)&&eq(a,c)))"
    "{"
      "float i=q(d,e)+q(e,y)+q(P(0,2),c)+q(c,P(2.,0.))+4.*q(z,a),w=q(b,z)+q(z,P(1,2))+q(x,a)+q(a,P(2.,1.))+4.*q(e,c);"
      "m.z=i<w&&neq(e,a)&&neq(e,z)?"
        "3.6*i<w?"
          "2:"
          "1:"
        "0;"
    "}"
  "if(!(eq(b,e)&&eq(d,z)||eq(b,d)&&eq(e,z)))"
    "{"
      "float i=q(P(-2.,1.),b)+q(b,x)+q(P(-1.,2.),z)+q(z,a)+4.*q(d,e),w=q(P(-2.,0.),d)+q(d,P(0.,2.))+q(u,e)+q(e,c)+4.*q(b,z);"
      "m.w=i>w&&neq(e,b)&&neq(e,z)?"
        "3.6*w<i?"
          "2:"
          "1:"
        "0;"
    "}"
  "if(!(eq(x,y)&&eq(e,a)||eq(x,e)&&eq(y,a)))"
    "{"
      "float i=q(b,x)+q(x,P(1.,-2.))+q(z,a)+q(a,P(2.,-1.))+4.*q(e,y),w=q(u,e)+q(e,c)+q(P(0.,-2.),y)+q(y,P(2.,0.))+4.*q(x,a);"
      "m.y=i>w&&neq(e,x)&&neq(e,a)?"
        "3.6*w<i?"
          "2:"
          "1:"
        "0;"
    "}"
  "if(!(eq(u,x)&&eq(b,e)||eq(u,b)&&eq(x,e)))"
    "{"
      "float i=q(P(-2.,0.),u)+q(u,P(0.,-2.))+q(d,e)+q(e,y)+4.*q(b,x),w=q(P(-2.,-1.),b)+q(b,z)+q(P(-1.,-2.),x)+q(x,a)+4.*q(u,e);"
      "m.x=i<w&&neq(e,b)&&neq(e,x)?"
        "3.6*i<w?"
          "2:"
          "1:"
        "0;"
    "}"
  "vec3 i=e;"
  "if(m.z!=0)"
    "{"
      "float w=q(a,d),T=q(z,y);"
      "bool l=m.z==2||!(m.y!=0&&!n(e,d)||m.w!=0&&!n(e,y)||n(d,z)&&n(z,c)&&n(c,a)&&n(a,y)&&!n(e,c));"
      "vec2 f=vec2(0,1./sqrt(2.)),r=vec2(1,-1);"
      "if(l)"
        "{"
          "bool F=2.2*w<=T&&neq(e,d)&&neq(b,d),A=2.2*T<=w&&neq(e,y)&&neq(x,y);"
          "f=F?"
            "vec2(0,.25):"
            "vec2(0,.5);"
          "r.x+=F?"
            "1.:"
            "0.;"
          "r.y-=A?"
            "1.:"
            "0.;"
        "}"
      "vec3 F=mix(z,a,step(q(e,a),q(e,z)));"
      "i=mix(i,F,n(v,f,r,s));"
    "}"
  "if(m.w!=0)"
    "{"
      "float w=q(z,u),T=q(b,c);"
      "bool l=m.w==2||!(m.z!=0&&!n(e,u)||m.x!=0&&!n(e,c)||n(u,b)&&n(b,d)&&n(d,z)&&n(z,c)&&!n(e,d));"
      "vec2 f=vec2(-1./sqrt(2.),0),r=vec2(1);"
      "if(l)"
        "{"
          "bool F=2.2*w<=T&&neq(e,u)&&neq(x,u),A=2.2*T<=w&&neq(e,c)&&neq(a,c);"
          "f=F?"
            "vec2(-.25,0):"
            "vec2(-.5,0);"
          "r.y+=F?"
            "1.:"
            "0.;"
          "r.x+=A?"
            "1.:"
            "0.;"
        "}"
      "vec3 F=mix(z,b,step(q(e,b),q(e,z)));"
      "i=mix(i,F,n(v,f,r,s));"
    "}"
  "if(m.y!=0)"
    "{"
      "float w=q(x,c),T=q(a,u);"
      "bool l=m.y==2||!(m.x!=0&&!n(e,c)||m.z!=0&&!n(e,u)||n(c,a)&&n(a,y)&&n(y,x)&&n(x,u)&&!n(e,y));"
      "vec2 f=vec2(1./sqrt(2.),0),r=vec2(-1);"
      "if(l)"
        "{"
          "bool F=2.2*w<=T&&neq(e,c)&&neq(z,c),A=2.2*T<=w&&neq(e,u)&&neq(b,u);"
          "f=F?"
            "vec2(.25,0):"
            "vec2(.5,0);"
          "r.y-=F?"
            "1.:"
            "0.;"
          "r.x-=A?"
            "1.:"
            "0.;"
        "}"
      "vec3 F=mix(a,x,step(q(e,x),q(e,a)));"
      "i=mix(i,F,n(v,f,r,s));"
    "}"
  "if(m.x!=0)"
    "{"
      "float w=q(b,y),T=q(x,d);"
      "bool l=m.x==2||!(m.w!=0&&!n(e,y)||m.y!=0&&!n(e,d)||n(y,x)&&n(x,u)&&n(u,b)&&n(b,d)&&!n(e,u));"
      "vec2 f=vec2(0,-1./sqrt(2.)),r=vec2(-1,1);"
      "if(l)"
        "{"
          "bool F=2.2*w<=T&&neq(e,y)&&neq(a,y),A=2.2*T<=w&&neq(e,d)&&neq(z,d);"
          "f=F?"
            "vec2(0,-.25):"
            "vec2(0,-.5);"
          "r.x-=F?"
            "1.:"
            "0.;"
          "r.y+=A?"
            "1.:"
            "0.;"
        "}"
      "vec3 F=mix(b,x,step(q(e,x),q(e,b)));"
      "i=mix(i,F,n(v,f,r,s));"
    "}"
  "FragColor=vec4(i,1);"
"}"
"\n#endif"