#pragma once

/* GLSL Vertex */
"#version 330\n"
  "layout(location=0) in vec2 Position;"
  "layout(location=1) in vec2 TexCoord;"
  "out vec2 v_TexCoord;"
  "uniform mat4 u_MVP;"
  "void main()"
  "{"
  "gl_Position=u_MVP*vec4(Position,0.,1.),v_TexCoord=TexCoord;"
  "}",

  /* GLSL Fragment */
  "#version 330\n"
  "uniform sampler2D u_Texture;"
  "in vec2 v_TexCoord;"
  "layout(location=0) out vec4 FragColor;"
  "vec2 v=vec2(640.,480.),d=1./v;"
  "float y=1.2,z=.06,r=1.12;"
  "vec3 t(vec3 F)"
  "{"
  "return mix(vec3(dot(F,vec3(.2126,.7152,.0722))),F,y);"
  "}"
  "vec3 s(vec3 F)"
  "{"
  "return F*r-z*r;"
  "}"
  "float e=1.,c=-1.1,w=.75,m=.03,a=.33;"
  "vec3 F=vec3(1.);"
  "vec3 s()"
  "{"
  "vec2 u=v_TexCoord;"
  "float z=.5*d.x,y=.5*d.y;"
  "vec2 v=vec2(z,y),t=vec2(-z,y),r=v*.5,x=t*.5,n=vec2(z,0.),s=vec2(0.,y);"
  "vec4 o=vec4(u-r,u-s),l=vec4(u-x,u+n),T=vec4(u+r,u+s),b=vec4(u+x,u-n),i=vec4(u-v,u-t),f=vec4(u+v,u+t);"
  "vec3 C=texture(u_Texture,u).xyz,g=texture(u_Texture,o.xy).xyz,p=texture(u_Texture,l.xy).xyz,D=texture(u_Texture,T.xy).xyz,Z=texture(u_Texture,b.xy).xyz,Y=texture(u_Texture,i.xy).xyz,X=texture(u_Texture,f.xy).xyz,W=texture(u_Texture,i.zw).xyz,V=texture(u_Texture,f.zw).xyz,U=texture(u_Texture,o.zw).xyz,S=texture(u_Texture,l.zw).xyz,R=texture(u_Texture,T.zw).xyz,Q=texture(u_Texture,b.zw).xyz;"
  "float P=dot(abs(Y-C),F),O=dot(abs(W-C),F),N=dot(abs(X-C),F),M=dot(abs(V-C),F),L=min(dot(abs(g-D),F),max(P,N)),K=min(dot(abs(p-Z),F),max(O,M)),J=K;"
  "if(N<P)"
  "J*=N/P;"
  "float I=L;"
  "if(M<O)"
  "I*=M/O;"
  "float H=K;"
  "if(P<N)"
  "H*=P/N;"
  "float G=L;"
  "if(O<M)"
  "G*=O/M;"
  "C=(J*Y+I*W+H*X+G*V+.001*C)/(J+I+H+G+.001);"
  "J=c*dot(abs(g-C)+abs(D-C),F)/(.125*dot(g+D,F)+a);"
  "I=c*dot(abs(p-C)+abs(Z-C),F)/(.125*dot(p+Z,F)+a);"
  "H=c*dot(abs(U-C)+abs(R-C),F)/(.125*dot(U+R,F)+a);"
  "G=c*dot(abs(S-C)+abs(Q-C),F)/(.125*dot(S+Q,F)+a);"
  "J=clamp(J+e,m,w);"
  "I=clamp(I+e,m,w);"
  "H=clamp(H+e,m,w);"
  "G=clamp(G+e,m,w);"
  "return(J*(g+D)+I*(p+Z)+H*(U+R)+G*(S+Q)+C)/(2.*(J+I+H+G)+1.);"
  "}"
  "void main()"
  "{"
  "FragColor=vec4(s(),1.),FragColor.xyz=t(FragColor.xyz),FragColor.xyz=s(FragColor.xyz);"
  "}",

  /* GLSL Compute */
  nullptr,
