#pragma once

"#ifdef VERTEX\n"
"layout(location=0) in vec2 Position;"
"layout(location=1) in vec2 TexCoord;"
"layout(location=2) in vec4 Color1;"
"layout(location=3) in vec4 Color2;"
"layout(location=4) in uint TexNum;"
"layout(location=5) in uint Flags;"
"uniform mat4 u_MVP;"
"out vec2 v_TexCoord;"
"out vec4 v_Color1,v_Color2;"
"flat out uint v_TexNum,v_Flags;"
"void main()"
"{"
  "gl_Position=u_MVP*vec4(Position,0,1);"
  "v_TexCoord=TexCoord;"
  "v_Color1=Color1.zyxw;"
  "v_Color2=Color2.wzyx;"
  "v_TexNum=TexNum;"
  "v_Flags=Flags;"
"}"
"\n#elif FRAGMENT\n"
"layout(location=0) out vec4 FragColor;"
"layout(location=1) out vec4 FragColorMap;layout(std140) uniform ubo_Colors{vec4 u_Palette[256];vec4 u_Gamma[256];};"
"uniform sampler2DArray u_Texture;"
"in vec2 v_TexCoord;"
"in vec4 v_Color1,v_Color2;"
"flat in uint v_TexNum,v_Flags;"
"\n#define checkFlag(a,b)(a&b)==b\n"
"void main()"
"{"
  "if(checkFlag(v_Flags,2u))"
    "FragColor=v_Color2;"
  "else "
    "{"
      "float v=texture(u_Texture,vec3(v_TexCoord,v_TexNum)).x;"
      "if(checkFlag(v_Flags,1u)&&v==0.)"
        "discard;"
      "FragColor=v_Color1*u_Palette[int(v*255)];"
    "}"
  "FragColor.x=u_Gamma[int(FragColor.x*255)].x;"
  "FragColor.y=u_Gamma[int(FragColor.y*255)].y;"
  "FragColor.z=u_Gamma[int(FragColor.z*255)].z;"
  "FragColor.w=checkFlag(v_Flags,4u)?"
    "v_Color2.w:"
    "1.;"
  "FragColorMap=vec4(0);"
  "if(checkFlag(v_Flags,8u))"
    "{"
      "FragColorMap=vec4(FragColor.xyz,.9);"
      "if(checkFlag(v_Flags,16u))"
        "FragColor=vec4(0);"
    "}"
"}"
"\n#endif"