#pragma once

"#ifdef VERTEX\n"
"layout(location=0) in vec2 Position;"
"layout(location=1) in vec2 TexCoord;"
"layout(location=2) in vec4 Color1;"
"layout(location=3) in vec4 Color2;"
"layout(location=4) in ivec2 TexIds;"
"layout(location=5) in ivec4 Flags;"
"layout(location=6) in vec2 Extra;"
"uniform mat4 u_MVP;"
"out vec2 v_TexCoord;"
"out vec4 v_Color1,v_Color2;"
"flat out ivec2 v_TexIds;"
"flat out ivec4 v_Flags;"
"out vec2 v_Extra;"
"void main()"
"{"
  "gl_Position=u_MVP*vec4(Position,0,1);"
  "v_TexCoord=TexCoord;"
  "v_Color1=Color1.wzyx;"
  "v_Color2=Color2.wzyx;"
  "v_TexIds=TexIds;"
  "v_Flags=Flags;"
  "v_Extra=Extra;"
"}"
"\n#elif FRAGMENT\n"
"layout(location=0) out vec4 FragColor;"
"uniform sampler2D u_Texture[16];"
"uniform sampler2DArray u_Textures[16];"
"in vec2 v_TexCoord;"
"in vec4 v_Color1,v_Color2;"
"flat in ivec2 v_TexIds;"
"flat in ivec4 v_Flags;"
"in vec2 v_Extra;"
"float v(vec3 v,float i,float y)"
"{"
  "float n=max(min(v.x,v.y),min(max(v.x,v.y),v.z)),l=max(i,1.)*(n-1.+.5*y);"
  "return clamp(l+.5,0.,1.);"
"}"
"void main()"
"{"
  "FragColor=vec4(1,0,0,1);"
  "switch(v_Flags.x){"
    "case 0:"
      "FragColor=texture(u_Texture[v_TexIds.x],v_TexCoord)*v_Color1;"
      "break;"
    "case 1:"
      "FragColor=texture(u_Textures[v_TexIds.x],vec3(v_TexCoord,v_TexIds.y))*v_Color1;"
      "break;"
    "case 2:"
      "FragColor=v_Color1;"
      "break;"
    "case 3:"
      "if(v_Flags.w==1)"
        "{"
          "float i=v(texture(u_Textures[v_TexIds.x],vec3(v_TexCoord,v_TexIds.y)).xyz,v_Extra.x,v_Extra.y+.1),n=v(texture(u_Textures[v_TexIds.x],vec3(v_TexCoord,v_TexIds.y)).xyz,v_Extra.x,.95);"
          "FragColor=vec4(mix(v_Color2.xyz,v_Color1.xyz,n),v_Color1.w*i);"
        "}"
      "else "
        "{"
          "float i=v(texture(u_Textures[v_TexIds.x],vec3(v_TexCoord,v_TexIds.y)).xyz,v_Extra.x,v_Extra.y);"
          "FragColor=vec4(v_Color1.xyz,v_Color1.w*i);"
        "}"
      "break;"
    "case 4:"
      "FragColor=v_Color1;"
      "break;"
  "}"
"}"
"\n#endif"