#pragma once

"#ifdef VERTEX\n"
"layout(location=0) in vec2 Position;"
"layout(location=1) in vec2 TexCoord;"
"layout(location=5) in ivec4 Flags;"
"uniform mat4 u_MVP;"
"out vec2 v_TexCoord;"
"flat out ivec4 v_Flags;"
"void main()"
"{"
  "gl_Position=u_MVP*vec4(Position,0,1);"
  "v_TexCoord=TexCoord;"
  "v_Flags=Flags;"
"}"
"\n#elif FRAGMENT\n"
"layout(location=0) out vec4 FragColor;"
"uniform sampler2D u_Texture0,u_Texture1;"
"in vec2 v_TexCoord;"
"flat in ivec4 v_Flags;"
"vec2 v=vec2(640,480),d=1./v;"
"\n#define CoefLuma vec3(0.2126,0.7152,0.0722)\n"
"vec3 t(vec3 m)"
"{"
  "return mix(vec3(dot(m,CoefLuma)),m,1.5);"
"}"
"vec3 s(vec3 m)"
"{"
  "return m*1.12-.0672;"
"}"
"float i=1.,n=-1.1,w=.75,x=.03,y=.33;"
"vec3 m=vec3(1);"
"\n#define P0(x)texture(u_Texture0,x).rgb\n"
"\n#define P1(x)texture(u_Texture1,x).rgb\n"
"vec3 s()"
"{"
  "vec2 v=v_TexCoord;"
  "float a=.5*d.x,z=.5*d.y;"
  "vec2 F=vec2(a,z),c=vec2(-a,z),C=F*.5,r=c*.5,s=vec2(a,0),u=vec2(0,z);"
  "vec4 P=vec4(v-C,v-u),l=vec4(v-r,v+s),A=vec4(v+C,v+u),D=vec4(v+r,v-s),E=vec4(v-F,v-c),G=vec4(v+F,v+c);"
  "int T=v_Flags.x;"
  "vec3 f=T==0?"
    "P0(v):"
    "P1(v),B=T==0?"
    "P0(P.xy):"
    "P1(P.xy),H=T==0?"
    "P0(l.xy):"
    "P1(l.xy),I=T==0?"
    "P0(A.xy):"
    "P1(A.xy),J=T==0?"
    "P0(D.xy):"
    "P1(D.xy),K=T==0?"
    "P0(E.xy):"
    "P1(E.xy),L=T==0?"
    "P0(G.xy):"
    "P1(G.xy),M=T==0?"
    "P0(E.zw):"
    "P1(E.zw),N=T==0?"
    "P0(G.zw):"
    "P1(G.zw),O=T==0?"
    "P0(P.zw):"
    "P1(P.zw),Q=T==0?"
    "P0(l.zw):"
    "P1(l.zw),R=T==0?"
    "P0(A.zw):"
    "P1(A.zw),S=T==0?"
    "P0(D.zw):"
    "P1(D.zw);"
  "float o=dot(abs(K-f),m),t=dot(abs(M-f),m),U=dot(abs(L-f),m),V=dot(abs(N-f),m),W=min(dot(abs(B-I),m),max(o,U)),X=min(dot(abs(H-J),m),max(t,V)),Y=X;"
  "if(U<o)"
    "Y*=U/o;"
  "float Z=W;"
  "if(V<t)"
    "Z*=V/t;"
  "float b=X;"
  "if(o<U)"
    "b*=o/U;"
  "float e=W;"
  "if(t<V)"
    "e*=t/V;"
  "f=(Y*K+Z*M+b*L+e*N+.001*f)/(Y+Z+b+e+.001);"
  "Y=n*dot(abs(B-f)+abs(I-f),m)/(.125*dot(B+I,m)+y);"
  "Z=n*dot(abs(H-f)+abs(J-f),m)/(.125*dot(H+J,m)+y);"
  "b=n*dot(abs(O-f)+abs(R-f),m)/(.125*dot(O+R,m)+y);"
  "e=n*dot(abs(Q-f)+abs(S-f),m)/(.125*dot(Q+S,m)+y);"
  "Y=clamp(Y+i,x,w);"
  "Z=clamp(Z+i,x,w);"
  "b=clamp(b+i,x,w);"
  "e=clamp(e+i,x,w);"
  "return(Y*(B+I)+Z*(H+J)+b*(O+R)+e*(Q+S)+f)/(2.*(Y+Z+b+e)+1.);"
"}"
"void main()"
"{"
  "FragColor=vec4(s(),1);"
  "FragColor.xyz=t(FragColor.xyz);"
  "FragColor.xyz=s(FragColor.xyz);"
"}"
"\n#endif"