#pragma once

"#ifdef VERTEX\n"
"layout(location=0) in vec2 Position;"
"layout(location=1) in vec2 TexCoord;"
"uniform mat4 u_MVP;"
"out vec2 v_TexCoord;"
"void main()"
"{"
  "gl_Position=u_MVP*vec4(Position,0,1);"
  "v_TexCoord=TexCoord;"
"}"
"\n#elif FRAGMENT\n"
"layout(location=0) out vec4 FragColor;"
"uniform sampler2D u_Texture;"
"in vec2 v_TexCoord;"
"vec2 v=vec2(640,480),d=1./v;"
"\n#define CoefLuma vec3(0.2126,0.7152,0.0722)\n"
"vec3 t(vec3 z)"
"{"
  "return mix(vec3(dot(z,CoefLuma)),z,1.5);"
"}"
"vec3 s(vec3 z)"
"{"
  "return z*1.12-.0672;"
"}"
"float n=1.,c=-1.1,w=.75,m=.03,y=.33;"
"vec3 z=vec3(1);"
"\n#define P(x)texture(u_Texture,x).rgb\n"
"vec3 s()"
"{"
  "vec2 v=v_TexCoord;"
  "float a=.5*d.x,x=.5*d.y;"
  "vec2 s=vec2(a,x),C=vec2(-a,x),e=s*.5,r=C*.5,A=vec2(a,0),D=vec2(0,x);"
  "vec4 F=vec4(v-e,v-D),l=vec4(v-r,v+A),u=vec4(v+e,v+D),E=vec4(v+r,v-A),G=vec4(v-s,v-C),H=vec4(v+s,v+C);"
  "vec3 i=P(v),B=P(F.xy),I=P(l.xy),J=P(u.xy),K=P(E.xy),L=P(G.xy),M=P(H.xy),N=P(G.zw),O=P(H.zw),Q=P(F.zw),R=P(l.zw),S=P(u.zw),T=P(E.zw);"
  "float t=dot(abs(L-i),z),U=dot(abs(N-i),z),V=dot(abs(M-i),z),W=dot(abs(O-i),z),X=min(dot(abs(B-J),z),max(t,V)),Y=min(dot(abs(I-K),z),max(U,W)),f=Y;"
  "if(V<t)"
    "f*=V/t;"
  "float o=X;"
  "if(W<U)"
    "o*=W/U;"
  "float Z=Y;"
  "if(t<V)"
    "Z*=t/V;"
  "float b=X;"
  "if(U<W)"
    "b*=U/W;"
  "i=(f*L+o*N+Z*M+b*O+.001*i)/(f+o+Z+b+.001);"
  "f=c*dot(abs(B-i)+abs(J-i),z)/(.125*dot(B+J,z)+y);"
  "o=c*dot(abs(I-i)+abs(K-i),z)/(.125*dot(I+K,z)+y);"
  "Z=c*dot(abs(Q-i)+abs(S-i),z)/(.125*dot(Q+S,z)+y);"
  "b=c*dot(abs(R-i)+abs(T-i),z)/(.125*dot(R+T,z)+y);"
  "f=clamp(f+n,m,w);"
  "o=clamp(o+n,m,w);"
  "Z=clamp(Z+n,m,w);"
  "b=clamp(b+n,m,w);"
  "return(f*(B+J)+o*(I+K)+Z*(Q+S)+b*(R+T)+i)/(2.*(f+o+Z+b)+1.);"
"}"
"void main()"
"{"
  "FragColor=vec4(s(),1);"
  "FragColor.xyz=t(FragColor.xyz);"
  "FragColor.xyz=s(FragColor.xyz);"
"}"
"\n#endif"