#pragma once

/* GLSL Vertex */
"#version 330\n"
"layout(location=0) in vec2 Position;"
"layout(location=1) in vec2 TexCoord;"
"layout(location=5) in ivec4 Flags;"
"uniform mat4 u_MVP;"
"out vec2 v_TexCoord;"
"flat out ivec4 v_Flags;"
"void main()"
"{"
  "gl_Position=u_MVP*vec4(Position,0.,1.),v_TexCoord=TexCoord,v_Flags=Flags;"
"}",

/* GLSL Fragment */
"#version 330\n"
"layout(location=0) out vec4 FragColor;layout(std140) uniform ubo_Metrics{float u_SharpStrength;float u_SharpClamp;float u_Radius;float pad1;vec2 u_RelSize;};"
"uniform sampler2D u_Textures[2];"
"in vec2 v_TexCoord;"
"flat in ivec4 v_Flags;"
"float t(vec3 s)"
"{"
  "return s.y*(.587/.299)+s.x;"
"}"
"vec3 u(vec3 v)"
"{"
  "vec2 u=v_TexCoord,s=u_RelSize;"
  "vec3 y=texture(u_Textures[v_Flags.y],u+vec2(0.,-s.y)).xyz,m=texture(u_Textures[v_Flags.y],u+vec2(-s.x,0.)).xyz,x=v,a=texture(u_Textures[v_Flags.y],u+vec2(s.x,0.)).xyz,z=texture(u_Textures[v_Flags.y],u+vec2(0.,s.y)).xyz;"
  "float f=t(y),d=t(m),e=t(x),r=t(a),i=t(z),p=min(e,min(min(f,d),min(i,r))),n=max(e,max(max(f,d),max(i,r))),l=n-p;"
  "if(l<max(.0625,n*.125))"
    "return x;"
  "vec3 b=y+m+x+a+z;"
  "float F=(f+d+r+i)*.25,o=abs(F-e),c=max(0.,o/l-.25)*(1./.75);"
  "c=min(.75,c);"
  "vec3 g=texture(u_Textures[v_Flags.y],u+vec2(-s.x,-s.y)).xyz,T=texture(u_Textures[v_Flags.y],u+vec2(s.x,-s.y)).xyz,S=texture(u_Textures[v_Flags.y],u+vec2(-s.x,s.y)).xyz,h=texture(u_Textures[v_Flags.y],u+vec2(s.x,s.y)).xyz;"
  "b+=g+T+S+h;"
  "b*=vec3(1./9.);"
  "float C=t(g),R=t(T),M=t(S),D=t(h),k=abs(.25*C+-.5*f+.25*R)+abs(.5*d+-1.*e+.5*r)+abs(.25*M+-.5*i+.25*D),Z=abs(.25*C+-.5*d+.25*M)+abs(.5*f+-1.*e+.5*i)+abs(.25*R+-.5*r+.25*D);"
  "bool Y=Z>=k;"
  "float X=Y?-s.y:-s.x;"
  "if(!Y)"
    "f=d,i=r;"
  "float W=abs(f-e),V=abs(i-e);"
  "f=(f+e)*.5;"
  "i=(i+e)*.5;"
  "if(W<V)"
    "f=i,f=i,W=V,X*=-1.;"
  "vec2 U;"
  "U.x=u.x+(Y?0.:X*.5);"
  "U.y=u.y+(Y?X*.5:0.);"
  "W*=.25;"
  "vec2 Q=U,P=Y?vec2(s.x,0.):vec2(0.,s.y);"
  "float O=f,N=f;"
  "bool L=false,K=false;"
  "U+=P*vec2(-1.,-1.);"
  "Q+=P*vec2(1.,1.);"
  "for(int J=0;J<16;J++)"
    "{"
      "if(!L)"
        "O=t(texture(u_Textures[v_Flags.y],U.xy).xyz);"
      "if(!K)"
        "N=t(texture(u_Textures[v_Flags.y],Q.xy).xyz);"
      "L=L||abs(O-f)>=W;"
      "K=K||abs(N-f)>=W;"
      "if(L&&K)"
        "break;"
      "if(!L)"
        "U-=P;"
      "if(!K)"
        "Q+=P;"
    "}"
  "float J=Y?u.x-U.x:u.y-U.y,I=Y?Q.x-u.x:Q.y-u.y;"
  "bool H=J<I;"
  "O=H?O:N;"
  "if(e-f<0.==O-f<0.)"
    "X=0.;"
  "float G=I+J;"
  "J=H?J:I;"
  "float E=(.5+J*(-1./G))*X;"
  "vec3 B=texture(u_Textures[v_Flags.y],vec2(u.x+(Y?0.:E),u.y+(Y?E:0.))).xyz;"
  "return vec3(-c)*B+(b*vec3(c)+B);"
"}"
"vec3 e(vec3 u)"
"{"
  "vec3 f=texture(u_Textures[v_Flags.y],v_TexCoord+u_RelSize*u_Radius).xyz,v=texture(u_Textures[v_Flags.y],v_TexCoord-u_RelSize*u_Radius).xyz,s=(f+v)/2.,i=u-s,m=vec3(.2126,.7152,.0722)*u_SharpStrength*1.5;"
  "vec4 y=vec4(m*(.5/u_SharpClamp),.5);"
  "float x=u_SharpClamp*2.*clamp(dot(vec4(i,1.),y),0.,1.)-u_SharpClamp;"
  "return clamp(u+x,0.,1.);"
"}"
"void main()"
"{"
  "vec3 y=texture(u_Textures[v_Flags.y],v_TexCoord).xyz;"
  "if(v_Flags.x==0)"
    "FragColor=vec4(e(y),1.);"
  "else "
     "FragColor=vec4(u(y),1.);"
"}",

/* GLSL Compute */
nullptr,